import { readFileSync } from "fs";
import { google } from "googleapis";
import { googleAuth } from "./google";

const FROM = process.env.NOTES_EMAIL_FROM || "maksim.makevich@tryllengine.com";
const COMPANY_DOMAIN = process.env.COMPANY_DOMAIN || "tryllengine.com";
const BRAND_NAVY = "#1f2d4a";

function readSignatureSource(): string {
  try {
    return readFileSync("assets/signature-source.html", "utf-8");
  } catch {
    return "";
  }
}

/** HTML подписи: <table>…</table> из assets/signature-source.html. */
function signatureHtml(): string {
  const m = readSignatureSource().match(/<table[\s\S]*?<\/table>/i);
  return m ? m[0] : "";
}

/** data:image base64 логотипа из подписи — переиспользуем в шапке карточки. */
function logoDataUri(): string {
  const m = readSignatureSource().match(/src="(data:image\/png;base64,[^"]+)"/i);
  return m ? m[1] : "";
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

/** HTML-карточка письма (email-safe: таблицы + инлайн-стили). */
export function notesEmailHtml(
  title: string,
  dateISO: string,
  docUrl: string,
  tldr: string[],
): string {
  const date = dateISO.slice(0, 10);
  const logo = logoDataUri();
  const logoImg = logo
    ? `<img src="${logo}" width="160" alt="Tryll Engine" style="display:inline-block;width:160px;height:auto;">`
    : `<div style="font-size:20px;font-weight:bold;color:${BRAND_NAVY};">TRYLL ENGINE</div>`;

  const tldrItems = (tldr || [])
    .slice(0, 6)
    .map((t) => `<li style="margin-bottom:6px;">${esc(t)}</li>`)
    .join("");
  const tldrBlock = tldrItems
    ? `<tr><td style="padding:8px 40px 0;">
         <div style="background:#f7f8fa;border:1px solid #eceef1;border-radius:8px;padding:16px 20px;">
           <div style="font-size:14px;font-weight:bold;color:#1a1a1a;padding-bottom:8px;">TL;DR</div>
           <ul style="margin:0;padding-left:20px;color:#333;font-size:13px;line-height:1.55;">${tldrItems}</ul>
         </div>
       </td></tr>`
    : "";

  return `
<div style="background:#f4f5f7;padding:24px 12px;font-family:Arial,Helvetica,sans-serif;">
  <table align="center" width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;background:#ffffff;border:1px solid #e6e8eb;border-radius:12px;">
    <tr><td style="padding:32px 40px 8px;text-align:center;">${logoImg}</td></tr>
    <tr><td style="padding:8px 40px 0;text-align:center;">
      <div style="font-size:20px;font-weight:bold;color:#1a1a1a;">Notes from "${esc(title)}"</div>
      <div style="font-size:14px;color:#777;padding-top:4px;">${date}</div>
    </td></tr>
    <tr><td style="padding:20px 40px;text-align:center;">
      <a href="${docUrl}" style="display:inline-block;background:${BRAND_NAVY};color:#ffffff;text-decoration:none;font-size:15px;font-weight:bold;padding:12px 30px;border-radius:8px;">Open meeting notes</a>
    </td></tr>
    <tr><td style="padding:0 40px;text-align:center;">
      <div style="font-size:12px;color:#999;font-style:italic;">Auto-generated by Tryll Meeting Notes — may contain errors. No reply needed.</div>
    </td></tr>
    ${tldrBlock}
    <tr><td style="padding:24px 40px 32px;">${signatureHtml()}</td></tr>
  </table>
</div>`;
}

function buildRawMessage(to: string, subject: string, html: string): string {
  const subjectEnc = `=?UTF-8?B?${Buffer.from(subject, "utf-8").toString("base64")}?=`;
  const mime = [
    `From: ${FROM}`,
    `To: ${to}`,
    `Subject: ${subjectEnc}`,
    "MIME-Version: 1.0",
    'Content-Type: text/html; charset="UTF-8"',
    "Content-Transfer-Encoding: base64",
    "",
    Buffer.from(html, "utf-8").toString("base64"),
  ].join("\r\n");
  return Buffer.from(mime, "utf-8")
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "");
}

/** Оставляем только адреса нашего домена (внешним гостям не пишем). */
export function filterDomainRecipients(emails: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const e of emails) {
    const addr = e.trim().toLowerCase();
    if (!addr.endsWith(`@${COMPANY_DOMAIN}`)) continue;
    if (seen.has(addr)) continue;
    seen.add(addr);
    out.push(addr);
  }
  return out;
}

/** Отправляет письмо-карточку со ссылкой на заметки от имени FROM всем recipients. */
export async function sendNotesEmail(
  recipients: string[],
  title: string,
  dateISO: string,
  docUrl: string,
  tldr: string[] = [],
): Promise<void> {
  if (recipients.length === 0) return;
  const gmail = google.gmail({ version: "v1", auth: googleAuth() });
  const subject = `Meeting notes - ${title} (${dateISO.slice(0, 10)})`;
  const html = notesEmailHtml(title, dateISO, docUrl, tldr);
  const raw = buildRawMessage(recipients.join(", "), subject, html);
  await gmail.users.messages.send({ userId: "me", requestBody: { raw } });
}
